name: Lint diagnostics
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [
            cppcheck, 
            cpplint, 
            flake8, 
            # pep257, 
            uncrustify, 
            xmllint]
          distro: [
            foxy,
            humble,
            rolling
          ]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: ${{ matrix.distro }}
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: ${{ matrix.distro }}
        linter: ${{ matrix.linter }}
        package-name:
          diagnostic_aggregator
          diagnostic_updater
          self_test
