name: Test diagnostics
on:
  pull_request:
  push:
    branches:
      - rolling
  schedule:
    # Run every week 
    - cron: '0 0 * * 0'

jobs:
  build_and_test:
    name: Build and test on ${{ matrix.distro }}
    strategy:
      fail-fast: false
        matrix:
          distro: [
            foxy,
            humble,
            rolling
          ]
    runs-on: 
      - ubuntu-20.04
        if: ${{ matrix.distro == 'foxy' }}
      - ubuntu-22.04
        if: ${{ matrix.distro == 'humble' || matrix.distro == 'rolling' }}
    steps:
      - uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.distro }}
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.distro }}
          package-name:
            diagnostic_aggregator
            diagnostic_common_diagnostics
            diagnostic_updater
            self_test
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
